<?php
/** RESA activity-log tab. */
defined( 'ABSPATH' ) || exit;
$summary_cards = array(
	'success'   => array( 'count' => $counts['success'], 'label' => __( 'موفق', 'torob-variable-exporter' ), 'tone' => 'success' ),
	'warning'   => array( 'count' => $counts['warning'], 'label' => __( 'هشدار', 'torob-variable-exporter' ), 'tone' => 'warning' ),
	'error'     => array( 'count' => $counts['error'], 'label' => __( 'خطا', 'torob-variable-exporter' ), 'tone' => 'error' ),
	'api_error' => array( 'count' => $counts['api_error'], 'label' => __( 'خطای ارتباط API', 'torob-variable-exporter' ), 'tone' => 'error' ),
	'invalid'   => array( 'count' => $counts['invalid'], 'label' => __( 'محصول نامعتبر', 'torob-variable-exporter' ), 'tone' => 'error' ),
);
$logs_url = add_query_arg( array( 'page' => 'tves-settings', 'tab' => 'logs' ), admin_url( 'admin.php' ) );
?>
<section class="tves-logs-screen">
	<div class="tves-tab-intro"><div><span class="tves-eyebrow">RESA / LOGS</span><h2><?php esc_html_e( 'گزارش فعالیت ترب', 'torob-variable-exporter' ); ?></h2><p><?php esc_html_e( 'رویدادهای کاتالوگ را مرور کنید، خطاها را جدا ببینید یا گزارش قابل ارسال دریافت کنید.', 'torob-variable-exporter' ); ?></p></div><span class="dashicons dashicons-chart-bar" aria-hidden="true"></span></div>
	<nav class="tves-log-summary" aria-label="<?php esc_attr_e( 'خلاصه وضعیت گزارش‌ها', 'torob-variable-exporter' ); ?>">
		<a class="tves-log-total tves-log-stat <?php echo '' === $status ? 'is-active' : ''; ?>" href="<?php echo esc_url( $logs_url ); ?>" data-status=""><span><?php esc_html_e( 'همه رویدادهای ثبت‌شده', 'torob-variable-exporter' ); ?></span><strong data-log-count="all"><?php echo esc_html( number_format_i18n( $counts['all'] ) ); ?></strong><small><?php esc_html_e( '۳۰ روز اخیر؛ حداکثر ۲۰٬۰۰۰ رویداد', 'torob-variable-exporter' ); ?></small></a>
		<div class="tves-log-breakdown"><?php foreach ( $summary_cards as $card_status => $card ) : $card_url = add_query_arg( 'status', $card_status, $logs_url ); ?><a class="tves-log-stat tves-log-stat-<?php echo esc_attr( $card['tone'] ); ?> <?php echo $status === $card_status ? 'is-active' : ''; ?>" href="<?php echo esc_url( $card_url ); ?>" data-status="<?php echo esc_attr( $card_status ); ?>"><span class="tves-log-stat-label"><i aria-hidden="true"></i><span><?php echo esc_html( $card['label'] ); ?></span></span><strong data-log-count="<?php echo esc_attr( $card_status ); ?>"><?php echo esc_html( number_format_i18n( $card['count'] ) ); ?></strong></a><?php endforeach; ?></div>
	</nav>

	<div class="tves-log-toolbar">
		<div class="tves-toolbar-section"><span class="tves-toolbar-icon dashicons dashicons-filter" aria-hidden="true"></span><div class="tves-toolbar-copy"><strong><?php esc_html_e( 'پایش رویدادها', 'torob-variable-exporter' ); ?></strong><span><?php esc_html_e( 'نوع رویداد را انتخاب کنید؛ جدول بی‌درنگ تازه می‌شود.', 'torob-variable-exporter' ); ?></span></div><form method="get" class="tves-log-filter tves-toolbar-group"><input type="hidden" name="page" value="tves-settings"><input type="hidden" name="tab" value="logs"><label for="tves-status-filter" class="screen-reader-text"><?php esc_html_e( 'نوع رویداد', 'torob-variable-exporter' ); ?></label><select id="tves-status-filter" name="status"><?php foreach ( $statuses as $value => $label ) : ?><option value="<?php echo esc_attr( $value ); ?>" <?php selected( $status, $value ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select><button type="submit" class="button tves-filter-submit"><?php esc_html_e( 'اعمال', 'torob-variable-exporter' ); ?></button></form><button type="button" class="button tves-refresh-logs" id="tves-refresh-logs"><span class="dashicons dashicons-update" aria-hidden="true"></span><span class="screen-reader-text"><?php esc_html_e( 'تازه‌سازی', 'torob-variable-exporter' ); ?></span></button></div>
		<div class="tves-toolbar-divider" aria-hidden="true"></div>
		<div class="tves-toolbar-section tves-toolbar-section-secondary"><span class="tves-toolbar-icon dashicons dashicons-download" aria-hidden="true"></span><div class="tves-toolbar-copy"><strong><?php esc_html_e( 'خروجی و نگه‌داری', 'torob-variable-exporter' ); ?></strong><span><?php esc_html_e( 'همه ردیف‌های فیلترشده را دریافت یا گزارش‌ها را پاک کنید.', 'torob-variable-exporter' ); ?></span></div><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="tves-log-export tves-toolbar-group"><input type="hidden" name="action" value="tves_export_logs"><input type="hidden" name="status" value="<?php echo esc_attr( $status ); ?>"><?php wp_nonce_field( 'tves_export_logs' ); ?><label for="tves-export-format" class="screen-reader-text"><?php esc_html_e( 'نوع فایل گزارش', 'torob-variable-exporter' ); ?></label><select id="tves-export-format" name="format"><option value="csv"><?php esc_html_e( 'CSV برای اکسل', 'torob-variable-exporter' ); ?></option><option value="txt"><?php esc_html_e( 'TXT متنی', 'torob-variable-exporter' ); ?></option></select><?php submit_button( __( 'دریافت', 'torob-variable-exporter' ), 'primary', 'download_logs', false ); ?></form><button type="button" class="button tves-clear-logs" id="tves-clear-logs"><span class="dashicons dashicons-trash" aria-hidden="true"></span><span><?php esc_html_e( 'پاک‌سازی', 'torob-variable-exporter' ); ?></span></button></div>
	</div>
	<div class="tves-ajax-notice" id="tves-log-notice" role="status" hidden></div>
	<div class="tves-log-results" id="tves-log-results" data-status="<?php echo esc_attr( $status ); ?>" data-paged="<?php echo esc_attr( $page ); ?>" aria-live="polite" aria-busy="false"><div class="tves-loading-state" role="status"><span class="tves-loader" aria-hidden="true"><i></i><i></i><i></i></span><strong><?php esc_html_e( 'در حال دریافت گزارش‌ها…', 'torob-variable-exporter' ); ?></strong></div><div class="tves-ajax-error" id="tves-log-error" role="alert" hidden></div><div id="tves-log-results-content"><?php include TVES_PATH . 'admin/logs-results.php'; ?></div></div>
</section>
