<?php
/** RESA product-output settings tab. */
defined( 'ABSPATH' ) || exit;
$enabled           = (string) ( $settings['enabled'] ?? 'yes' );
$v3_enabled        = (string) ( $settings['v3_enabled'] ?? 'yes' );
$title_format      = (string) ( $settings['title_format'] ?? 'parent_attributes' );
$title_attributes  = (array) ( $settings['title_attributes'] ?? array() );
$export_attributes = (array) ( $settings['export_attributes'] ?? array() );
?>
<form method="post" action="options.php" class="tves-settings-form">
	<?php settings_fields( 'tves_settings_group' ); ?><input type="hidden" name="tves_settings[settings_section]" value="output">
	<section class="tves-panel">
		<div class="tves-panel-heading"><span class="dashicons dashicons-products" aria-hidden="true"></span><div><h2><?php esc_html_e( 'تنظیم خروجی محصولات', 'torob-variable-exporter' ); ?></h2><p><?php esc_html_e( 'مشخص کنید چه اطلاعاتی و با چه عنوانی برای ترب ارسال شود.', 'torob-variable-exporter' ); ?></p></div></div>
		<div class="tves-field-stack">
			<div class="tves-field tves-field-toggle"><div><strong><?php esc_html_e( 'درگاه رسمی API نسخه ۳', 'torob-variable-exporter' ); ?></strong><p><?php esc_html_e( 'برای پاسخ به درخواست‌های امن ترب باید روشن بماند.', 'torob-variable-exporter' ); ?></p></div><label class="tves-switch"><input type="checkbox" name="tves_settings[v3_enabled]" value="1" <?php checked( 'yes', $v3_enabled ); ?>><span aria-hidden="true"></span><b><?php esc_html_e( 'API فعال باشد', 'torob-variable-exporter' ); ?></b></label></div>
			<div class="tves-field tves-field-toggle"><div><strong><?php esc_html_e( 'ارسال جداگانه انتخاب‌های محصول متغیر', 'torob-variable-exporter' ); ?></strong><p><?php esc_html_e( 'هر رنگ، اندازه یا انتخاب قابل خرید به‌صورت یک محصول مستقل در ترب نمایش داده می‌شود.', 'torob-variable-exporter' ); ?></p></div><label class="tves-switch"><input type="checkbox" name="tves_settings[enabled]" value="1" <?php checked( 'yes', $enabled ); ?>><span aria-hidden="true"></span><b><?php esc_html_e( 'انتخاب‌ها جدا ارسال شوند', 'torob-variable-exporter' ); ?></b></label></div>
			<div class="tves-field"><label class="tves-field-label" for="tves-title-format"><?php esc_html_e( 'ساختار عنوان در ترب', 'torob-variable-exporter' ); ?></label><div class="tves-control"><select id="tves-title-format" name="tves_settings[title_format]"><option value="parent_attributes" <?php selected( $title_format, 'parent_attributes' ); ?>><?php esc_html_e( 'نام محصول + ویژگی انتخاب‌شده', 'torob-variable-exporter' ); ?></option><option value="parent" <?php selected( $title_format, 'parent' ); ?>><?php esc_html_e( 'فقط نام محصول اصلی', 'torob-variable-exporter' ); ?></option><option value="custom" <?php selected( $title_format, 'custom' ); ?>><?php esc_html_e( 'الگوی دلخواه', 'torob-variable-exporter' ); ?></option></select><p><?php esc_html_e( 'حالت پیشنهادی باعث می‌شود هر انتخاب در نتایج ترب قابل تشخیص باشد.', 'torob-variable-exporter' ); ?></p></div></div>
			<div class="tves-field tves-template-row"><label class="tves-field-label" for="tves-title-template"><?php esc_html_e( 'الگوی دلخواه عنوان', 'torob-variable-exporter' ); ?></label><div class="tves-control"><input class="regular-text" dir="ltr" id="tves-title-template" name="tves_settings[title_template]" value="<?php echo esc_attr( $settings['title_template'] ?? '{parent} - {attributes}' ); ?>"><p><?php esc_html_e( 'از {parent}، {attributes} یا عبارتی مانند {attribute:pa_color} استفاده کنید.', 'torob-variable-exporter' ); ?></p></div></div>
			<div class="tves-field"><span class="tves-field-label"><?php esc_html_e( 'ویژگی‌های عنوان', 'torob-variable-exporter' ); ?></span><div class="tves-control tves-checkbox-list"><?php if ( ! $attributes ) : ?><em><?php esc_html_e( 'برای شناسایی ویژگی‌ها، یک‌بار کاتالوگ را بازسازی کنید.', 'torob-variable-exporter' ); ?></em><?php endif; ?><?php foreach ( $attributes as $slug => $label ) : ?><label><input type="checkbox" name="tves_settings[title_attributes][]" value="<?php echo esc_attr( $slug ); ?>" <?php checked( in_array( $slug, $title_attributes, true ) ); ?>><span><?php echo esc_html( $label ); ?></span><code dir="ltr"><?php echo esc_html( $slug ); ?></code></label><?php endforeach; ?><p><?php esc_html_e( 'اگر موردی انتخاب نشود، همه ویژگی‌های محصول در عنوان قابل استفاده‌اند.', 'torob-variable-exporter' ); ?></p></div></div>
			<div class="tves-field"><span class="tves-field-label"><?php esc_html_e( 'مشخصات ارسالی برای ترب', 'torob-variable-exporter' ); ?></span><div class="tves-control tves-checkbox-list"><?php foreach ( $attributes as $slug => $label ) : ?><label><input type="checkbox" name="tves_settings[export_attributes][]" value="<?php echo esc_attr( $slug ); ?>" <?php checked( in_array( $slug, $export_attributes, true ) ); ?>><span><?php echo esc_html( $label ); ?></span><code dir="ltr"><?php echo esc_html( $slug ); ?></code></label><?php endforeach; ?><p><?php esc_html_e( 'اگر موردی انتخاب نشود، همه ویژگی‌ها در فیلد spec ارسال می‌شوند.', 'torob-variable-exporter' ); ?></p></div></div>
			<div class="tves-field"><label class="tves-field-label" for="tves-sync-interval"><?php esc_html_e( 'زمان‌بندی بازسازی خودکار', 'torob-variable-exporter' ); ?></label><div class="tves-control"><select id="tves-sync-interval" name="tves_settings[sync_interval]"><option value="manual" <?php selected( $settings['sync_interval'] ?? 'manual', 'manual' ); ?>><?php esc_html_e( 'فقط دستی', 'torob-variable-exporter' ); ?></option><option value="hourly" <?php selected( $settings['sync_interval'] ?? '', 'hourly' ); ?>><?php esc_html_e( 'هر یک ساعت', 'torob-variable-exporter' ); ?></option><option value="six_hours" <?php selected( $settings['sync_interval'] ?? '', 'six_hours' ); ?>><?php esc_html_e( 'هر ۶ ساعت', 'torob-variable-exporter' ); ?></option><option value="daily" <?php selected( $settings['sync_interval'] ?? '', 'daily' ); ?>><?php esc_html_e( 'روزی یک‌بار', 'torob-variable-exporter' ); ?></option></select><p><?php esc_html_e( 'قیمت، موجودی و محصولات تازه با این زمان‌بندی در کاتالوگ ثبت می‌شوند.', 'torob-variable-exporter' ); ?></p></div></div>
			<details class="tves-advanced-field"><summary><?php esc_html_e( 'تنظیمات اتصال قدیمی (برای کاربران فنی)', 'torob-variable-exporter' ); ?></summary><div><label class="tves-field-label" for="tves-api-token"><?php esc_html_e( 'توکن خروجی قدیمی', 'torob-variable-exporter' ); ?></label><input type="password" autocomplete="new-password" class="regular-text" dir="ltr" id="tves-api-token" name="tves_settings[api_token]" value="<?php echo esc_attr( $settings['api_token'] ?? '' ); ?>"><p><?php esc_html_e( 'این مقدار فقط برای خروجی قدیمی GET است و در API نسخه ۳ استفاده نمی‌شود.', 'torob-variable-exporter' ); ?></p></div></details>
		</div>
	</section>
	<div class="tves-form-actions"><div><strong><?php esc_html_e( 'تنظیم خروجی آماده است؟', 'torob-variable-exporter' ); ?></strong><span><?php esc_html_e( 'پس از ذخیره، از نمای کلی کاتالوگ را بازسازی کنید.', 'torob-variable-exporter' ); ?></span></div><?php submit_button( __( 'ذخیره تنظیم خروجی', 'torob-variable-exporter' ), 'primary', 'submit', false ); ?></div>
</form>
