<?php
/** RESA overview tab. */
defined( 'ABSPATH' ) || exit;
$v3_enabled    = (string) ( $settings['v3_enabled'] ?? 'yes' );
$api_ready     = 'yes' === $v3_enabled && $v3_crypto_ready;
$catalog_ready = ! empty( $v3_stats['ready'] );
$sync_state    = $status['running'] ? 'running' : 'ready';
?>
<section class="tves-overview" id="tves-overview">
	<div class="tves-signal-rail" aria-label="<?php esc_attr_e( 'مسیر ارتباط فروشگاه با ترب', 'torob-variable-exporter' ); ?>">
		<div class="tves-signal <?php echo $api_ready ? 'is-ready' : 'is-alert'; ?>"><span class="tves-signal-dot" aria-hidden="true"></span><span><strong><?php esc_html_e( 'ارتباط امن API', 'torob-variable-exporter' ); ?></strong><small><?php echo $api_ready ? esc_html__( 'اعتبارسنجی توکن آماده است', 'torob-variable-exporter' ) : esc_html__( 'تنظیمات API یا Sodium را بررسی کنید', 'torob-variable-exporter' ); ?></small></span></div>
		<div class="tves-signal <?php echo $catalog_ready ? 'is-ready' : 'is-alert'; ?>"><span class="tves-signal-dot" aria-hidden="true"></span><span><strong><?php esc_html_e( 'کاتالوگ محصولات', 'torob-variable-exporter' ); ?></strong><small id="tves-v3-catalog-status"><?php echo $catalog_ready ? esc_html( sprintf( __( '%d آیتم آماده ارسال است', 'torob-variable-exporter' ), $v3_stats['total'] ) ) : esc_html__( 'ابتدا کاتالوگ را بازسازی کنید', 'torob-variable-exporter' ); ?></small></span></div>
		<div class="tves-signal is-<?php echo esc_attr( $sync_state ); ?>" id="tves-sync-signal"><span class="tves-signal-dot" aria-hidden="true"></span><span><strong><?php esc_html_e( 'همگام‌سازی', 'torob-variable-exporter' ); ?></strong><small id="tves-sync-status"><?php echo $status['running'] ? esc_html__( 'در حال پردازش', 'torob-variable-exporter' ) : esc_html__( 'آماده', 'torob-variable-exporter' ); ?></small></span></div>
	</div>

	<div class="tves-overview-grid">
		<article class="tves-api-console">
			<div class="tves-console-heading"><div><h2><?php esc_html_e( 'درگاه رسمی محصولات ترب (API نسخه ۳)', 'torob-variable-exporter' ); ?></h2><p><?php esc_html_e( 'این همان نشانی است که باید در اختیار پشتیبانی ترب قرار بگیرد.', 'torob-variable-exporter' ); ?></p></div><span class="tves-state-pill <?php echo $api_ready ? 'is-positive' : 'is-negative'; ?>"><?php echo $api_ready ? esc_html__( 'امن و فعال', 'torob-variable-exporter' ) : esc_html__( 'نیازمند بررسی', 'torob-variable-exporter' ); ?></span></div>
			<div class="tves-endpoint" dir="ltr"><code id="tves-v3-endpoint"><?php echo esc_html( $v3_feed_url ); ?></code><button type="button" class="button tves-copy-button" data-copy-target="tves-v3-endpoint" data-label="<?php esc_attr_e( 'کپی نشانی', 'torob-variable-exporter' ); ?>" data-success="<?php esc_attr_e( 'کپی شد', 'torob-variable-exporter' ); ?>"><span class="dashicons dashicons-admin-page" aria-hidden="true"></span><span><?php esc_html_e( 'کپی نشانی', 'torob-variable-exporter' ); ?></span></button></div>
			<dl class="tves-fact-list"><div><dt><?php esc_html_e( 'دامنه‌های مجاز', 'torob-variable-exporter' ); ?></dt><dd dir="ltr"><?php echo esc_html( implode( ' / ', $v3_audiences ) ); ?></dd></div><div><dt><?php esc_html_e( 'اعتبارسنجی امنیتی', 'torob-variable-exporter' ); ?></dt><dd><?php echo $v3_crypto_ready ? esc_html__( 'آماده؛ افزونه PHP Sodium فعال است', 'torob-variable-exporter' ) : esc_html__( 'افزونه PHP Sodium روی سرور فعال نیست', 'torob-variable-exporter' ); ?></dd></div><div><dt><?php esc_html_e( 'آخرین درخواست ترب', 'torob-variable-exporter' ); ?></dt><dd id="tves-v3-last-access"><?php echo $v3_last_access ? esc_html( wp_date( 'Y-m-d H:i:s', $v3_last_access ) ) : esc_html__( 'هنوز درخواستی ثبت نشده', 'torob-variable-exporter' ); ?></dd></div></dl>
			<details class="tves-legacy-endpoint"><summary><?php esc_html_e( 'نشانی قدیمی خروجی (نسخه ۱)', 'torob-variable-exporter' ); ?></summary><p><?php esc_html_e( 'این نشانی فقط برای سازگاری نگه‌داری شده است و نباید به‌عنوان API نسخه ۳ ارسال شود.', 'torob-variable-exporter' ); ?></p><div class="tves-endpoint" dir="ltr"><code id="tves-v1-endpoint"><?php echo esc_html( $feed_url ); ?></code><button type="button" class="button tves-copy-button" data-copy-target="tves-v1-endpoint" data-label="<?php esc_attr_e( 'کپی نشانی', 'torob-variable-exporter' ); ?>" data-success="<?php esc_attr_e( 'کپی شد', 'torob-variable-exporter' ); ?>"><span><?php esc_html_e( 'کپی نشانی', 'torob-variable-exporter' ); ?></span></button></div></details>
		</article>

		<article class="tves-sync-monitor" id="tves-sync-card" data-running="<?php echo $status['running'] ? '1' : '0'; ?>">
			<div class="tves-monitor-heading"><div class="tves-catalog-metric"><span><?php esc_html_e( 'آیتم آماده ارسال به ترب', 'torob-variable-exporter' ); ?></span><strong id="tves-exported-count"><?php echo esc_html( number_format_i18n( $status['exported_items'] ) ); ?></strong></div><span class="tves-live-indicator"><i aria-hidden="true"></i><span id="tves-live-label"><?php echo $status['running'] ? esc_html__( 'در حال پردازش', 'torob-variable-exporter' ) : esc_html__( 'آماده', 'torob-variable-exporter' ); ?></span></span></div>
			<div class="tves-progress" role="progressbar" aria-label="<?php esc_attr_e( 'پیشرفت بازسازی کاتالوگ', 'torob-variable-exporter' ); ?>" aria-valuemin="0" aria-valuemax="100" aria-valuenow="<?php echo esc_attr( $status['percent'] ); ?>"><span id="tves-progress-bar" style="width: <?php echo esc_attr( $status['percent'] ); ?>%"></span></div>
			<p class="tves-progress-copy" id="tves-progress-label" aria-live="polite"><?php echo esc_html( sprintf( __( '%1$d محصول از مجموع %2$d محصول بررسی شده است', 'torob-variable-exporter' ), $status['processed'], $status['total'] ) ); ?></p>
			<dl class="tves-monitor-facts"><div><dt><?php esc_html_e( 'آخرین تکمیل موفق', 'torob-variable-exporter' ); ?></dt><dd id="tves-last-sync"><?php echo $status['last'] ? esc_html( wp_date( 'Y-m-d H:i', $status['last'] ) ) : esc_html__( 'هنوز انجام نشده', 'torob-variable-exporter' ); ?></dd></div><div><dt><?php esc_html_e( 'اجرای بعدی', 'torob-variable-exporter' ); ?></dt><dd id="tves-next-sync"><?php echo $status['next'] ? esc_html( wp_date( 'Y-m-d H:i', $status['next'] ) ) : esc_html__( 'فقط اجرای دستی', 'torob-variable-exporter' ); ?></dd></div><div><dt><?php esc_html_e( 'آخرین فعالیت پردازشگر', 'torob-variable-exporter' ); ?></dt><dd id="tves-last-activity"><?php echo $status['last_activity'] ? esc_html( wp_date( 'Y-m-d H:i:s', $status['last_activity'] ) ) : esc_html__( 'هنوز فعالیتی ثبت نشده', 'torob-variable-exporter' ); ?></dd></div><div><dt><?php esc_html_e( 'بازیابی خودکار / تلاش مجدد', 'torob-variable-exporter' ); ?></dt><dd id="tves-recovery-count"><?php echo esc_html( (string) $status['recovery_count'] . ' / ' . (string) $status['total_retries'] ); ?></dd></div></dl>
		</article>
	</div>

	<section class="tves-sync-panel">
		<div class="tves-sync-illustration" aria-hidden="true"><span></span><span></span><span></span></div><div><h2><?php esc_html_e( 'بازسازی کامل کاتالوگ', 'torob-variable-exporter' ); ?></h2><p><?php esc_html_e( 'پس از تغییر تنظیمات، قیمت یا موجودی، کاتالوگ را تازه کنید. نسخه قبلی تا پایان پردازش برای ترب در دسترس می‌ماند.', 'torob-variable-exporter' ); ?></p></div>
		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="tves-manual-sync"><input type="hidden" name="action" value="tves_manual_sync"><?php wp_nonce_field( 'tves_manual_sync' ); ?><?php submit_button( __( 'شروع بازسازی کاتالوگ', 'torob-variable-exporter' ), 'primary', 'submit', false ); ?></form>
	</section>
</section>
